name = "0xjwlabs/luauhono"
version = "0.1.0"
private = true
authors = ["0xJWLabs <hi@0xjwlabs.xyz>"]
repository = "https://github.com/0xJWLabs/luauhono"
license = "MIT"

includes = ["src/**/*", "pesde.toml", "LICENSE"]

[engines]
lune = "^0.9.4"

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
